repos:
  - repo: https://github.com/axiros/axblack
    rev: v2020.11.12 # Replace by any tag/version: https://github.com/axiros/axblack/tags
    hooks:
      - id: black
        language_version: python3.9 # Should be a command that runs python3.6+